---
title: "3_figures"
format: html
editor: visual
---

```{r, message=FALSE, error=FALSE}
source("R/libraries.R")
source("R/functions.R")
source("R/data_files_and_results.R")
source("R/metadata.R")

knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)

set.seed(123)
```

Single protein, delta

```{r}
ggplot(df_long_l2fc[df_long_l2fc$protein == 'KLHL41',], aes(x=intervention, y=l2fc, fill=intervention))+
    geom_violin(trim = TRUE, width=1, color=NA, alpha=0.5)+
    geom_boxplot(width=0.25, color="black", fill="white", alpha=0.5)+
    geom_jitter(size=5, width=0.03)+
    geom_hline(yintercept=0, linetype="dashed")+
    scale_fill_manual(values=c("#0078b0", "#c41b1b"))+
    scale_x_discrete(labels=c("Resistance", "Terbutaline"))+
    theme(panel.background = element_rect(fill = "transparent", colour = NA),
          plot.background = element_rect(fill = "transparent", colour = NA),
          axis.line = element_line(colour = "black"),
          legend.position = "none",
          text = element_text(size = 20),
          axis.text.x= element_text(color="black"),
          axis.text.y= element_text(color="black")
          )+
    ylab("Log2fold change")+
    xlab("Fiber type")

```

Several specific proteins, delta

```{r}

df_long_l2fc %>% 
    dplyr::filter(protein=="KLHL41" | protein=="AKR1C2" | protein=="AKR1C3") %>% 
    ggplot(aes(x=protein, y=l2fc, group=intervention))+
    geom_violin(trim = TRUE, width=1, color=NA, alpha=0.5, aes(group=interaction(protein, intervention), fill=intervention))+
    geom_boxplot(aes(group=interaction(protein, intervention)), width=0.25, color="black", alpha=0.5, position =position_dodge(width=1))+
    geom_jitter(size=3, position = position_dodge(width=1), alpha=0.5)+
    geom_hline(yintercept=0, linetype="dashed")+
    scale_fill_manual(values=c("#0078b0", "#c41b1b"))+
    theme(panel.background = element_rect(fill = "transparent", colour = NA),
          plot.background = element_rect(fill = "transparent", colour = NA),
          axis.line = element_line(colour = "black"),
          legend.position = "right",
          text = element_text(size = 20),
          axis.text.x= element_text(color="black"),
          axis.text.y= element_text(color="black")
          )+
    ylab("Log2fold change")+
    xlab("Protein")

```

Several proteins of the same family

```{r}
df_long_l2fc %>% 
    dplyr::filter(grepl('KLHL41', protein)) %>% 
    ggplot(aes(x=protein, y=l2fc, group=intervention))+
    #geom_violin(trim = TRUE, width=1, color=NA, alpha=0.5, aes(group=interaction(protein, intervention), fill=intervention))+
    geom_boxplot(aes(group=interaction(protein, intervention)), width=0.25, color="black", alpha=0.5, position =position_dodge(width=1))+
    #geom_jitter(size=3, position = position_dodge(width=1), alpha=0.5)+
    geom_hline(yintercept=0, linetype="dashed")+
    scale_fill_manual(values=c("#0078b0", "#c41b1b"))+
    theme(panel.background = element_rect(fill = "transparent", colour = NA),
          plot.background = element_rect(fill = "transparent", colour = NA),
          axis.line = element_line(colour = "black"),
          legend.position = "right",
          text = element_text(size = 20),
          axis.text.x= element_text(angle = 90, vjust = 0.5, hjust=1, color="black", size=12),
          axis.text.y= element_text(color="black")
          )+
    ylab("Log2fold change")+
    xlab("Protein")

```

Specific GO-term (bars)

```{r}
df_long_l2fc_mean %>% 
    dplyr::filter(grepl('GO:0006412', go)) %>% 
    dplyr::filter(intervention == "terbutaline") %>% 
    ggplot(aes(x=l2fc_mean, y=reorder(protein, l2fc_mean)))+
    geom_col(aes(fill=regulated), na.rm=TRUE)+
    #geom_violin(trim = TRUE, width=1, color=NA, alpha=0.5, aes(group=interaction(protein, intervention), fill=intervention))+
    #geom_boxplot(aes(group=interaction(protein, intervention)), width=0.25, color="black", alpha=0.5, position =position_dodge(width=1))+
    #geom_jitter(size=3, position = position_dodge(width=1), alpha=0.5)+
    geom_vline(xintercept=0)+
    scale_fill_manual(values=c("#0078b0", "#c41b1b"))+
    theme(panel.background = element_rect(fill = "transparent", colour = NA),
          plot.background = element_rect(fill = "transparent", colour = NA),
          axis.line = element_line(colour = "black"),
          legend.position = "right",
          text = element_text(size = 20),
          axis.text.x= element_text(angle = 90, vjust = 0.5, hjust=1, color="black", size=12),
          axis.text.y= element_text(color="black")
          )+
    ylab("Protein")+
    xlab("Log2fold change")+
    xlim(-0.2, 1.5)

ggsave('data/figures/go_translation_ter.pdf', height = 15, width = 10)

```

Specific GO-term (RES; points) WORK ON SCALING

```{r}
df_long_l2fc_mean %>% 
    dplyr::filter(grepl('GO:0006412', go)) %>% 
    dplyr::filter(intervention == "resistance") %>% 
    ggplot(aes(x=l2fc_mean, y=reorder(protein, l2fc_mean)))+
    geom_point(aes(color=regulated, size=q), alpha=0.5, na.rm=TRUE)+
    scale_size(range = c(0, 8), name="q-value", trans = 'reverse')+
    #geom_violin(trim = TRUE, width=1, color=NA, alpha=0.5, aes(group=interaction(protein, intervention), fill=intervention))+
    #geom_boxplot(aes(group=interaction(protein, intervention)), width=0.25, color="black", alpha=0.5, position =position_dodge(width=1))+
    #geom_jitter(size=3, position = position_dodge(width=1), alpha=0.5)+
    geom_hline(yintercept=0, linetype="dashed")+
    scale_color_manual(values=c("#0078b0", "#c41b1b"))+
    theme(panel.background = element_rect(fill = "transparent", colour = NA),
          plot.background = element_rect(fill = "transparent", colour = NA),
          axis.line = element_line(colour = "black"),
          legend.position = "right",
          text = element_text(size = 20, family = "Source Sans Pro"),
          axis.text.x= element_text(angle = 90, vjust = 0.5, hjust=1, color="black", size=12),
          axis.text.y= element_text(color="black"),
          panel.border = element_rect(colour = "black", fill=NA, size=1)
          )+
    ylab("Log2fold change")+
    xlab("Protein")

ggsave('data/figures/go_translation_bubble.pdf', height = 15, width = 5)

```

Top10 most upregulated and downregulated proteins

```{r}

top_proteins(df_long_l2fc_mean, "terbutaline", 10, q)+
    xlim(-1, 2)

top_proteins(df_long_l2fc_mean, "resistance", 10, q)+
    xlim(-1, 2)

```

Correlation with hypertrophy

```{r}
correlations_ter(df_long_l2fc, 10)

correlations_res(df_long_l2fc, 10)

```

```{r}
correlation <- merge(df_long_l2fc, (metadata %>% dplyr::select("delta_lean")), by.x="sample", by.y="row.names", all.x=T)

correlation$delta_lean <- as.numeric(as.character(correlation$delta_lean))

correlation <- correlation %>%
    group_by(protein, intervention) %>%
    summarise(cor = stats::cor.test(l2fc, delta_lean)$cor,
              p = stats::cor.test(l2fc, delta_lean)$p) %>%
    ungroup()

```
